# Generated by Django 4.0.1 on 2022-01-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='payment',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
