# Generated by Django 4.0.1 on 2022-01-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_paymentinfo_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='type',
            field=models.CharField(choices=[('DEBIT', 'DEBIT'), ('CREDIT', 'CREDIT')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
