# Generated by Django 4.0.1 on 2022-01-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_alter_paymentinfo_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('company', models.CharField(choices=[('JIO', 'JIO'), ('BSNL', 'BSNL'), ('Airtel', 'Airtel'), ('VI', 'VI')], default='JIO', max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
