# Generated by Django 4.0.1 on 2022-01-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0005_siminfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siminfo',
            name='company',
            field=models.CharField(choices=[('JIO', 'JIO'), ('Airtel', 'Airtel'), ('VI', 'VI'), ('BSNL', 'BSNL')], default='JIO', max_length=10),
        ),
    ]
