# Generated by Django 4.0.1 on 2022-01-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0006_alter_siminfo_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='aadhar',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='payment',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='siminfo',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='siminfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='siminfo',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
